apiVersion: v1
kind: PersistentVolume
metadata:
  name: source-volume
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: "/Users/robbwinkle/git/blendededge/openintegrationhub"
  persistentVolumeReclaimPolicy: Retain
